<?xml version="1.0" encoding="utf-8"?><Database Name="PlotterDA" Class="PlotterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=IT-PC2\SQLEXPRESS;Initial Catalog=PlotterDA;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="PlotterDAConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Acknowledge" Member="Acknowledges">
    <Type Name="Acknowledge">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Device_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Event_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Event_DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Instrument" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Event" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ack_Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ack_User" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ack_DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="Role" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ModefiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifiedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsRowEnable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Authority" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Signature" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password_expiry_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Password_Expiry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email_notification" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="sms_notification" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Department_User" Member="Department" ThisKey="Department_Id" OtherKey="Department_Id" Type="Department" IsForeignKey="true" />
      <Association Name="Role_User" Member="Role1" ThisKey="Role" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Company_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="Department_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Department_Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Department_Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Department_User" Member="Users" ThisKey="Department_Id" OtherKey="Department_Id" Type="User" />
      <Association Name="Department_Device_Config" Member="Device_Configs" ThisKey="Department_Id" OtherKey="Department_Id" Type="Device_Config" />
    </Type>
  </Table>
  <Table Name="dbo.Device_Config" Member="Device_Configs">
    <Type Name="Device_Config">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="E_Port" Type="System.String" DbType="NChar(4)" CanBeNull="true" />
      <Column Name="Channel_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Port_No" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Instrument" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Interval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Alarm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Last_Record" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifiedDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsRowActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Rh_Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Upper_Limit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lower_Limit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Upper_Range" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lower_Range" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Device_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Offset" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="dateofCalibration" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Lower" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="higher" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Department_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NetworkID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Department_Device_Config" Member="Department" ThisKey="Department_Id" OtherKey="Department_Id" Type="Department" IsForeignKey="true" />
      <Association Name="Device_Enum_Device_Config" Member="Device_Enum" ThisKey="Device_Type" OtherKey="ID" Type="Device_Enum" IsForeignKey="true" />
      <Association Name="Network_Device_Config" Member="Network" ThisKey="NetworkID" OtherKey="ID" Type="Network" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Device_Enum" Member="Device_Enums">
    <Type Name="Device_Enum">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Device_Enum_Device_Config" Member="Device_Configs" ThisKey="ID" OtherKey="Device_Type" Type="Device_Config" />
    </Type>
  </Table>
  <Table Name="dbo.Email" Member="Emails">
    <Type Name="Email">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Delivered_Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Date_Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventLog" Member="EventLogs">
    <Type Name="EventLog">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EventName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MessageLog" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="DeviceID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Channel_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Port_Id" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[_Data]" Member="_Data" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="date_" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Network" Member="Networks">
    <Type Name="Network">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Port" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Channel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Network_Device_Config" Member="Device_Configs" ThisKey="ID" OtherKey="NetworkID" Type="Device_Config" />
    </Type>
  </Table>
  <Table Name="dbo.ofsetAuditRecord" Member="ofsetAuditRecords">
    <Type Name="ofsetAuditRecord">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Device_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ofset" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="createdby" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="createddatetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="Id" OtherKey="Role" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.SMS" Member="SMs">
    <Type Name="SM">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SMS_Number" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Delivered_Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Date_Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYSProperties" Member="SYSProperties">
    <Type Name="SYSProperty">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Signature" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Automatic_Sign" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IP_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Port1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Port2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Parity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StopBit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RTS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DTS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="D_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="D_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Number_Devices" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SMS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="backuplocation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lastbakdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idlog" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="passlog" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="serverinstance" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Client_Info" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Connected_Client" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Power_Acknowledged" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Acknowledged" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Alert_Interval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Power_SMS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AlarmEnable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Alarm_IP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Alarm_Port" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EmailPassword" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EmailSMTP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailPort" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SMSID" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SMSPassword" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SMSSecret" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SMSToken" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GSM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WebLink" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Create_dbBackup" Method="Create_dbBackup">
    <Parameter Name="dbName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="location" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="Create_dbBackupResult">
      <Column Name="ErrorMessage" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Update_Acknowladge" Method="Update_Acknowladge">
    <Parameter Name="Ack_User" Parameter="ack_User" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ID" Parameter="iD" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Ack_Comments" Parameter="ack_Comments" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Get_Acknowladge" Method="Get_Acknowladge">
    <ElementType Name="Get_AcknowladgeResult">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Device_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Event_Type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Event_DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Instrument" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Event" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Ack_Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ack_User" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ack_DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Insert_Acknowladge_TMP" Method="Insert_Acknowladge_TMP">
    <Parameter Name="ID" Parameter="iD" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Device_ID" Parameter="device_ID" Type="System.Guid" DbType="UniqueIdentifier" />
    <Parameter Name="Location" Parameter="location" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Instrument" Parameter="instrument" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Event_Type" Parameter="event_Type" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Event_DateTime" Parameter="event_DateTime" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Event" Parameter="event" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Data" Parameter="data" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Insert_User" Method="Insert_User" IsComposable="true">
    <Parameter Name="User_Name" Parameter="user_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="Role" Parameter="role" Type="System.Int32" DbType="Int" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Full_Name" Parameter="full_Name" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Authority" Parameter="authority" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Department" Parameter="department" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Signature" Parameter="signature" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password_expiry_date" Parameter="password_expiry_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Password_Expiry" Parameter="password_Expiry" Type="System.Int32" DbType="Int" />
    <Parameter Name="sms_notification" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="email_notification" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="object" />
  </Function>
  <Function Name="dbo.sp_Update_User" Method="sp_Update_User" IsComposable="true">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_Name" Parameter="user_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="Role" Parameter="role" Type="System.Int32" DbType="Int" />
    <Parameter Name="CreatedBy" Parameter="createdBy" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Full_Name" Parameter="full_Name" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Authority" Parameter="authority" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Department" Parameter="department" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Active" Parameter="active" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Signature" Parameter="signature" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password_expiry_date" Parameter="password_expiry_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Password_Expiry" Parameter="password_Expiry" Type="System.Int32" DbType="Int" />
    <Parameter Name="sms_notification" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="email_notification" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="object" />
  </Function>
</Database>